### PR TITLE
Support `pyarrow.Table` with `geoarrow.pyarrow` extension types as geometry columns

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Work-in-progress, and haven't yet tested it.

The idea is that when encountering a `geoarrow.pyarrow` extension type, to convert this to its raw storage field with metadata (i.e. how the extension type looks like in IPC or when the python wrapper class is not registered). Short term, this is the easiest approach, because a lot of the existing code relies on checking eg the "ARROW:extension:name" in the field metadata.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
This works now, but it still requires you to ensure you are passing interleaved coordinates, and not one of the other geoarrow types (separated, or wkb/wkt). We could also do that conversion automatically.

Should probably factor out the added code into a helper function somewhere.

**Comment by kylebarron** [comment]
> This works now, but it still requires you to ensure you are passing interleaved coordinates, and not one of the other geoarrow types (separated, or wkb/wkt). We could also do that conversion automatically.
> 
> Should probably factor out the added code into a helper function somewhere.

For now I'd be happy to just assert that the coordinates are interleaved, and handle separated/wkt/wkb in the future

**Review by kylebarron — APPROVED** [review]

**Comment by kylebarron** [comment]
this lgtm! Anything else you wanted to do before merging?

**Comment by kylebarron** [comment]
In #308 I now check for pycapsule interface methods but don't yet handle pyarrow extension types

**Pull request merged**
